const test=require('node:test');const assert=require('node:assert/strict');
const {parsePresentationPlan,validatePresentationPlan,buildPresentationPlanFallback}=require('../src/content/presentationContract');
function plan(severity='watch'){return{schemaVersion:'1.0',severity,priority:severity,visualVariant:severity,cards:[{id:'hero',role:severity==='unknown'?'uncertainty':severity==='critical'?'action':'hero',title:'สถานการณ์น้ำ',body:severity==='unknown'?'ยังยืนยันข้อมูลไม่ได้':'ติดตามสถานการณ์น้ำและข้อมูลล่าสุด',items:[],cta:[]}],spokenText:'รายงานสถานการณ์น้ำครับ',spokenSections:[],audioStyle:{tone:severity==='critical'?'urgent':'friendly',pacing:'natural',detailLevel:'detailed',emphasis:['สถานการณ์น้ำ']},actions:['ติดตามข้อมูล'],warnings:[],factsUsed:['flood.severity']}}
test('validates all five presentation variants',()=>{for(const s of ['normal','watch','affected','critical','unknown']){const r=parsePresentationPlan(plan(s));assert.equal(r.ok,true,r.errors?.join('; '));}});
test('rejects severity drift',()=>{const p=plan('watch');p.severity='critical';assert.ok(validatePresentationPlan(p,{expectedSeverity:'watch'}).length);});
test('critical requires immediate action on card 1',()=>{const p=plan('critical');p.cards[0].body='สถานการณ์น้ำกำลังเปลี่ยนแปลง';assert.ok(validatePresentationPlan(p).some(x=>x.includes('critical')));});
test('unknown requires explicit uncertainty',()=>{const p=plan('unknown');p.cards[0].body='สถานการณ์น้ำล่าสุด';assert.ok(validatePresentationPlan(p).some(x=>x.includes('unknown')));});
test('rejects unsupported certainty and forbidden topics',()=>{const p=plan();p.spokenText='ปลอดภัยแน่นอนและราคาปาล์มวันนี้';assert.ok(validatePresentationPlan(p).some(x=>x.includes('unsupported')));});
test('fallback preserves verified severity and adaptive audio policy',()=>{const r=buildPresentationPlanFallback({floodSituation:{severity:'watch',summary:'ควรเฝ้าระวัง',actions:['ติดตามระดับน้ำ']},weatherAnalysis:{current:{description:{label:'มีเมฆ'}}},report:{spokenText:'รายงานครับ',shortSummary:'เฝ้าระวัง'}});assert.equal(r.severity,'watch');assert.equal(r.audioSelectionPolicy,'gemini-adaptive-within-verified-facts');assert.ok(r.spokenText);});
